version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - ../backend_static:/backend_static
      - ../media:/media

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    build: .
    env_file: .env
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../backend_static:/backend_static
      - ../media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
