# Generated by Django 3.2.3 on 2023-08-27 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug может содержать только буквы, цифры, дефисы и символ подчеркивания.', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
