# Generated by Django 3.2.3 on 2023-09-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
