# Generated by Django 3.2.3 on 2023-08-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_auto_20230827_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
