# Generated by Django 3.2.3 on 2023-08-27 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_ingredient_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
    ]
