# Generated by Django 3.2.3 on 2023-08-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
