# Generated by Django 3.2.3 on 2023-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_recipe_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
