# Generated by Django 3.2.3 on 2023-08-29 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_rename_quantity_recipeingredient_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="amount",
            new_name="quantity",
        ),
    ]
