# Generated by Django 3.2.3 on 2023-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_favoriterecipe"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="recipes.Recipe"
            ),
        ),
    ]
